language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
#  - "pypy"
env:
  - DJANGO_VERSION=1.4.5
  - DJANGO_VERSION=1.5.1
before_install:
  - export PIP_USE_MIRRORS=true
  - export PIP_INDEX_URL=https://simple.crate.io/
  - export DJANGO_SETTINGS_MODULE=floppyforms.test_settings
  - sudo apt-get update
  - sudo apt-get install binutils gdal-bin libproj-dev libgeos-c1
install:
  - pip install -e .
  - pip install -r requirements/tests.txt Django==$DJANGO_VERSION
before_script:
  - (python --version 2>&1 | grep -q "Python 2" && flake8 floppyforms --ignore=E5,E123,E125,E126) || echo "Skipped flake8 check (python 3)"
script:
  - make test
branches:
  only:
    - master
notifications:
  irc:
    channels:
      - "irc.freenode.org#django-floppyforms"
    on_success: change
    on_failure: always
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO_VERSION=1.4.5
